class BibleBook {
  final String name;
  final String testament;

  BibleBook({required this.name, required this.testament});
}

final List<BibleBook> oldTestamentBooks = [
  BibleBook(name: 'Génesis', testament: 'Antiguo'),
  BibleBook(name: 'Éxodo', testament: 'Antiguo'),
  BibleBook(name: 'Levítico', testament: 'Antiguo'),
  BibleBook(name: 'Números', testament: 'Antiguo'),
  BibleBook(name: 'Deuteronomio', testament: 'Antiguo'),
  BibleBook(name: 'Josué', testament: 'Antiguo'),
  BibleBook(name: 'Jueces', testament: 'Antiguo'),
  BibleBook(name: 'Rut', testament: 'Antiguo'),
  BibleBook(name: '1 Samuel', testament: 'Antiguo'),
  BibleBook(name: '2 Samuel', testament: 'Antiguo'),
  BibleBook(name: '1 Reyes', testament: 'Antiguo'),
  BibleBook(name: '2 Reyes', testament: 'Antiguo'),
  BibleBook(name: '1 Crónicas', testament: 'Antiguo'),
  BibleBook(name: '2 Crónicas', testament: 'Antiguo'),
  BibleBook(name: 'Esdras', testament: 'Antiguo'),
  BibleBook(name: 'Nehemías', testament: 'Antiguo'),
  BibleBook(name: 'Ester', testament: 'Antiguo'),
  BibleBook(name: 'Job', testament: 'Antiguo'),
  BibleBook(name: 'Salmos', testament: 'Antiguo'),
  BibleBook(name: 'Proverbios', testament: 'Antiguo'),
  BibleBook(name: 'Eclesiastés', testament: 'Antiguo'),
  BibleBook(name: 'Cantares', testament: 'Antiguo'),
  BibleBook(name: 'Isaías', testament: 'Antiguo'),
  BibleBook(name: 'Jeremías', testament: 'Antiguo'),
  BibleBook(name: 'Lamentaciones', testament: 'Antiguo'),
  BibleBook(name: 'Ezequiel', testament: 'Antiguo'),
  BibleBook(name: 'Daniel', testament: 'Antiguo'),
  BibleBook(name: 'Oseas', testament: 'Antiguo'),
  BibleBook(name: 'Joel', testament: 'Antiguo'),
  BibleBook(name: 'Amós', testament: 'Antiguo'),
  BibleBook(name: 'Abdías', testament: 'Antiguo'),
  BibleBook(name: 'Jonás', testament: 'Antiguo'),
  BibleBook(name: 'Miqueas', testament: 'Antiguo'),
  BibleBook(name: 'Nahúm', testament: 'Antiguo'),
  BibleBook(name: 'Habacuc', testament: 'Antiguo'),
  BibleBook(name: 'Sofonías', testament: 'Antiguo'),
  BibleBook(name: 'Hageo', testament: 'Antiguo'),
  BibleBook(name: 'Zacarías', testament: 'Antiguo'),
  BibleBook(name: 'Malaquías', testament: 'Antiguo'),
];

final List<BibleBook> newTestamentBooks = [
  BibleBook(name: 'Mateo', testament: 'Nuevo'),
  BibleBook(name: 'Marcos', testament: 'Nuevo'),
  BibleBook(name: 'Lucas', testament: 'Nuevo'),
  BibleBook(name: 'Juan', testament: 'Nuevo'),
  BibleBook(name: 'Hechos', testament: 'Nuevo'),
  BibleBook(name: 'Romanos', testament: 'Nuevo'),
  BibleBook(name: '1 Corintios', testament: 'Nuevo'),
  BibleBook(name: '2 Corintios', testament: 'Nuevo'),
  BibleBook(name: 'Gálatas', testament: 'Nuevo'),
  BibleBook(name: 'Efesios', testament: 'Nuevo'),
  BibleBook(name: 'Filipenses', testament: 'Nuevo'),
  BibleBook(name: 'Colosenses', testament: 'Nuevo'),
  BibleBook(name: '1 Tesalonicenses', testament: 'Nuevo'),
  BibleBook(name: '2 Tesalonicenses', testament: 'Nuevo'),
  BibleBook(name: '1 Timoteo', testament: 'Nuevo'),
  BibleBook(name: '2 Timoteo', testament: 'Nuevo'),
  BibleBook(name: 'Tito', testament: 'Nuevo'),
  BibleBook(name: 'Filemón', testament: 'Nuevo'),
  BibleBook(name: 'Hebreos', testament: 'Nuevo'),
  BibleBook(name: 'Santiago', testament: 'Nuevo'),
  BibleBook(name: '1 Pedro', testament: 'Nuevo'),
  BibleBook(name: '2 Pedro', testament: 'Nuevo'),
  BibleBook(name: '1 Juan', testament: 'Nuevo'),
  BibleBook(name: '2 Juan', testament: 'Nuevo'),
  BibleBook(name: '3 Juan', testament: 'Nuevo'),
  BibleBook(name: 'Judas', testament: 'Nuevo'),
  BibleBook(name: 'Apocalipsis', testament: 'Nuevo'),
];
